version: "3"
services:
  react-app:
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/code/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build: .
    volumes: 
      - ./src:/code/src
    command: ["npm", "run", "test"]
